config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    authenticated :student do
      resources :events, module: "student", :only => [:show, :index]
    end
    authenticated :instructor do
      resources :events, module: "instructor"
    end
    root to: "dashboard/dashboard#index"
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_for :students
  devise_for :instructors

  resources :events
  resources :users
  resources :students
  resources :instructors

  root "dashboard/dashboard#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true

end

app/models/instructor.rb
class Instructor < User
  has_many :events
end

app/models/student.rb
class Student < User
  has_and_belongs_to_many :events

end

app/models/user.rb
class User < ApplicationRecord

  enum user_role: [:student, :instructor]
  has_many :events

  # belongs_to :instructor, :class_name => 'User'


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :call_event
  before_action :owned_event

  def index
    @events = Event.all
  end

  def new
    @event = current_user.events.new
  end


    def create
      @event = current_user.events.new(event_params)
      if @event.save
        redirect_to @event
      else
        render 'new'
      end
    end

  def show

  end

  def edit

  end

  def update

    @event.update(event_params)
    redirect_to(event_path(@event))
  end

  def destroy

    @event.destroy
    redirect_to events_path
  end

private

  def event_params
    params.require(:event).permit(:date)
  end

  def call_event
    @event = Event.find_by(params[:id])
  end

  def owned_event
    unless current_user == @event.user
      redirect_to root_path
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    devise_group :user, contains: [:student, :instructor]
    after_create :set_role

    def set_role
      @user = User.find(params[:id])
      @user.student_id = User.student.index(@user)
    end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :user_role, :student_id)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :user_role, :student_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/dashboard/dashboard/index.html.erb
<h1>~THE DASHBOARD~</h1>

app/views/events/edit.html.erb
<h1>EDIT AN EVENT!</h1>


<%= simple_form_for @event do |f| %>
  <%= f.input :date %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Cancel", event_path(@event) %>

app/views/events/index.html.erb
<h1>THIS IS THE EVENT INDEX</h1>


<hr>
<% @events.each do |event| %>
<ul><%= link_to event.date, event_path(event) %></ul>
<% end %>

app/views/events/new.html.erb
<h1>NEW EVENT</h1>

<%= simple_form_for @event do |f| %>
  <%= f.input :date %>
  <%= f.button :submit %>
<% end %>

app/views/events/show.html.erb
<h1>INDIVIDUAL EVENT SHOW PAGE</h1>

<hr>

<%= @event.date %>

<hr>

<ul><%= link_to "Event Index", events_path %></ul>

<ul><%= link_to "Edit Post", edit_event_path(@event) %></ul>

  <ul><%= link_to "Delete Event", event_path(@event), method: :delete, data: { confirm: "Are you sure you want to delete this event?" } %></ul>

app/views/layouts/_navbar.html.erb
        <%= link_to "Home", '/' %>
        <%= link_to "All Events", events_path %>

          <% if user_signed_in? %>
            <p>Hello, <%= current_user.email %>!</p>
            <li>
            <% if current_user.user_role != "student" %>
            <%= link_to "New Event", new_event_path %>

                <% end %>

            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "Login", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Register", new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowSeason</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/navbar' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>